### ISSUE TITLE
Why the group id of this module is com.github.chhsiao90 ?

### ISSUE THREAD

**Issue by abccbaandy** [modelmapper/modelmapper-module-java8#15]
Is it history reason?

Since it's under official github now, maybe change that too?

**Comment by chhsiao90** [comment]
Yes, it's history reason.

I can change it and have a new release.

**Comment by abccbaandy** [comment]
Hi, sry for brother you.

I see you already have this "fix" merge into master branch, but I can't find the commit in master commit log and no release ofc.

Am I miss something?
