### ISSUE TITLE
No JAR in Maven Central

### ISSUE THREAD

**Issue by jacek99** [modelmapper/modelmapper-module-java8#17]
https://repo1.maven.org/maven2/com/github/chhsiao90/modelmapper-module-java8/1.2.1/

There is POM, etc...but no JAR. Unable to download it via Gradle.

**Comment by marcusvoltolim** [comment]
How to add the module to a maven project?

**Comment by chhsiao90** [comment]
Use [modelmapper-module-jsr310](https://search.maven.org/artifact/com.github.chhsiao90/modelmapper-module-jsr310/1.2.1/jar).
