### ISSUE TITLE
Use instance of DateTimeFormatter instead of format string in Jsr310ModuleConfig

### ISSUE THREAD

**Issue by gadton** [modelmapper/modelmapper-module-java8#2]
I would like to have a way to pass an instance of DateTimeFormatter to Jsr310ModuleConfig instead of a format string. This would enable to use additional features of the formatter (caseInsensitive, ...) and to use the defined formatters like DateTimeFormatter.ISO_OFFSET_DATE_TIME.

**Comment by chhsiao90** [comment]
The feature was released at v1.2.1

**Comment by jdmcmahan** [comment]
Was this ever released to Maven Central? I'm not finding 1.2.1 anywhere.

**Comment by chhsiao90** [comment]
I guessed I forgot to close and release the archive from the sonatype staging repository. It should be available now!
